batch_size: 32

train_dogs_path: 'D:\matvei\datasets\dogs_and_cats\training_set\dogs'
train_cats_path: 'D:\matvei\datasets\dogs_and_cats\training_set\cats'
test_dogs_path: 'D:\matvei\datasets\dogs_and_cats\test_set\dogs'
test_cats_path: 'D:\matvei\datasets\dogs_and_cats\test_set\cats'

optimizer:
  name: adam
  lr: 1e-3
  momentum: 0.5


network:
  arch: resnet

  in_nc: 3
  base_nc: 64
  out_nc: 2
  
  block_type: classic