batch_size: 16

train_dogs_path: 'D:\matvei\datasets\dogs_and_cats\training_set\dogs'
train_cats_path: 'D:\matvei\datasets\dogs_and_cats\training_set\cats'
test_dogs_path: 'D:\matvei\datasets\dogs_and_cats\test_set\dogs'
test_cats_path: 'D:\matvei\datasets\dogs_and_cats\test_set\cats'

network:
  in_nc: 3
  base_nc: 64
  out_nc: 2